codecov:
  require_ci_to_pass: no

coverage:
  status:
    # https://docs.codecov.com/docs/commit-status#project-status
    project:
      default:
        only_pulls: true
    # https://docs.codecov.com/docs/commit-status#patch-status
    patch:
      default:
        only_pulls: true

# https://docs.codecov.com/docs/pull-request-comments#disable-comment
comment: false
