import Editor from "./Editor.js";

if(typeof ROLLUP_DEFINES_APPLIED === "undefined" || !ROLLUP_DEFINES_APPLIED){
	//this code is generated by editor/build.mjs
	/*start build defines*/
	window["EDITOR_ENV"] = "dev";
	/*end build defines*/
}

let editor = new Editor();
export default editor;

editor.init();
