# This workflow will build the editor and engine and place it in an artifact
# so that it can be deployed by one of the deployment workflows.
# This workflow is largely the same as ci.yml, unfortunately we have to duplicate
# a lot of code because GitHub doesn't support reusing steps (https://github.com/actions/runner/issues/748).
# The reason why the build step is separated into its own workflow file is to
# make PR deployment faster, since we don't have to wait for tests etc. to
# succeed in order to deploy a PR preview.
# However, these same build steps still have to be included in ci.yml because
# in the case of deploying to canary/production we do want to make sure all
# steps succeed before deploying.

name: Build

on:
  pull_request:
    branches: [main]

jobs:
  Build:
    runs-on: ubuntu-latest

    env:
      DENO_DIR: deno_dir
      PUPPETEER_DOWNLOAD_PATH: deno_dir/deno_puppeteer/chromium/
      PUPPETEER_CHROMIUM_REVISION: 991974

    # All these steps are the same as in ci.yml except for some if conditions,
    # so if you make any changes you'll probably want to change them there as well
    steps:
      - name: Setup repo
        uses: actions/checkout@v2

      - name: Setup Deno
        # For more information see: https://github.com/denoland/setup-deno
        uses: denoland/setup-deno@004814556e37c54a2f6e31384c9e18e983317366
        with:
          deno-version: "1.25.1"

      - name: Cache Deno dependencies
        uses: actions/cache@v3
        with:
          # Using the import map as key doesn't necessarily cause the cache to
          # get invalidated in all cases. A script could still import a url
          # directly for example. But this is good enough in most cases.
          # If the cache wasn't invalidated, this simply means some of the
          # dependencies are downloaded on every run, which is fine as long as
          # there are not too many uncached dependencies.
          # If at a later point it turns out using only the importmap as key
          # is not enough, we can add more files here.
          key: denoDeps-${{ hashFiles('importmap.json') }}
          path: ${{ env.DENO_DIR }}

      - name: npm install
        run: npm install

      - name: Create Deno types hash file
        # Creates a file that is used as hash key for the cache in the next step.
        run: deno task dev --create-cache-hashfile

      - name: Cache Deno types
        uses: actions/cache@v3
        with:
          key: denoTypes-${{ hashFiles('.denoTypes/cacheHashfile') }}
          path: .denoTypes

      - name: Cache npm packages
        uses: actions/cache@v3
        with:
          key: npmPackages-${{ hashFiles('scripts/dev.js') }}
          path: npm_packages

      - name: Setup Renda
        # Sets up a development environment required for type the next steps to pass.
        run: deno task dev --no-serve

      - name: Install editor dependencies
        run: deno task build-editor-dependencies

      # Build
      - name: Build engine
        run: deno task build

      - name: Build editor
        run: deno task build-editor-release

      - name: Tar build files
        run: |
          cd editor/dist
          tar -czf ../../build_files.tar *

      - name: Write PR data
        env:
          PULL_REQUEST_NUMBER: ${{ github.event.number }}
        run: |
          echo $PULL_REQUEST_NUMBER > pr.txt

      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: |
            build_files.tar
            pr.txt
