name: build
on:
  workflow_call:
    inputs:
      build-commit-sha:
        required: false
        type: string

env:
  # be sure to also update these in other workflows
  DENO_DIR: deno_dir
  DENO_VERSION: "1.42.3"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup repo
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8

      - name: Cache
        uses: actions/cache@9b0c1fce7a93df8e3bb8926b0d6e9d89e92f20a7
        with:
          path: |
            deno_dir
            .denoTypes
            npm_packages
            studio/deps
          key: ci-${{ github.run_id }}_${{ github.run_attempt }}
          restore-keys: ci-

      - name: Setup Deno
        uses: denoland/setup-deno@041b854f97b325bd60e53e9dc2de9cb9f9ac0cba
        with:
          deno-version: ${{ env.DENO_VERSION }}

      - name: Build engine
        run: deno task build-engine

      - name: Build studio
        env:
          BUILD_COMMIT_SHA: ${{ inputs.build-commit-sha }}
        run: deno task build-studio

      - name: Tar build files
        run: |
          cd studio/dist
          tar -czf ../../build_files.tar *

      - name: Write PR data
        env:
          PULL_REQUEST_NUMBER: ${{ github.event.number }}
        run: |
          echo $PULL_REQUEST_NUMBER > pr.txt

      - name: Upload build artifact
        uses: actions/upload-artifact@83fd05a356d7e2593de66fc9913b3002723633cb
        with:
          name: build
          path: |
            build_files.tar
            pr.txt
