# Publishes a package to npm when a GitHub release is created
name: Publish npm
on:
  release:
    types: [published]

env:
  # be sure to also update these in other workflows
  DENO_DIR: deno_dir
  DENO_VERSION: "1.32.1"

permissions: {}
jobs:
  build-and-release:
    runs-on: ubuntu-latest
    environment: publish_npm
    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8

      - name: Setup Deno
        uses: denoland/setup-deno@9db7f66e8e16b5699a514448ce994936c63f0d54
        with:
          deno-version: ${{ env.DENO_VERSION }}

      - name: Build package
        run: deno task build-npm-package ${{ github.event.release.tag_name }}

      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
      - run: cd npmPackage && npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
